Repository hyperapp/fx, pull requests merged in 2018-03, with the labels that each got.

#26 Update README.md
  README.md
Labels: DOCS

#27 Created debounce & throttle effects
  README.md
  src/fxCreators.js
  src/fxTypes.js
  src/makeDefaultFx.js
  test/withFx.test.js
Labels: API, DISCUSSION, FEATURE

#28 Empty/no-op fx
  README.md
  src/withFx.js
  test/withFx.test.js
Labels: BUG

#33 Jest update
  .gitignore
  test/withFx.test.js
Labels: BUG, TESTING

#20 Update Jest
  .gitignore
  package.json
  src/withFx.js
  test/withFx.test.js
Labels: BUG, HELP WANTED, TESTING

#31 window.fx => window.hyperappFx
  README.md
  package.json
Labels: BREAKING, DOCS

#32 Subviews
  README.md
  package.json
  src/withFx.js
  test/withFx.test.js
Labels: FEATURE
